import { Html, Main, Head, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Calibri%3A400%2C700%2C400italic%2C700italic&fbclid=IwAR1WHXJqEbuxmHcbfmQEYBEfgx4zqhsNejs5nQegTmiijRsPxAImWRxGKys&display=optional"
          rel="stylesheet"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}